-- MySQL Script generated by MySQL Workbench
-- Ter 17 Mai 2016 17:53:57 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `ID_Veiculo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Ano` VARCHAR(45) NOT NULL COMMENT '',
  `Quilometragem` VARCHAR(45) NULL COMMENT '',
  `Placa` VARCHAR(45) NOT NULL COMMENT '',
  `Marca` VARCHAR(45) NOT NULL COMMENT '',
  `Modelo` VARCHAR(45) NOT NULL COMMENT '',
  `Categoria` VARCHAR(45) NOT NULL COMMENT '',
  `Renavam` VARCHAR(45) NOT NULL COMMENT '',
  `EstadoConservacao` MEDIUMTEXT NULL COMMENT '',
  `ComentariosAdicionais` MEDIUMTEXT NULL COMMENT '',
  PRIMARY KEY (`ID_Veiculo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `ID_Funcionario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(45) NOT NULL COMMENT '',
  `NumeroRegistro` VARCHAR(45) NOT NULL COMMENT '',
  `RG` VARCHAR(45) NOT NULL COMMENT '',
  `CPF` VARCHAR(45) NOT NULL COMMENT '',
  `CNH` VARCHAR(45) NOT NULL COMMENT '',
  `ComentariosAdicionais` MEDIUMTEXT NULL COMMENT '',
  `Senha` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Funcionario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viagem` (
  `ID_Viagem` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `DataSaida` VARCHAR(45) NOT NULL COMMENT '',
  `DataChegada` VARCHAR(45) NOT NULL COMMENT '',
  `QuilometragemSaida` VARCHAR(45) NOT NULL COMMENT '',
  `QuilometragemChegada` VARCHAR(45) NOT NULL COMMENT '',
  `RelatorioDanos` MEDIUMTEXT NULL COMMENT '',
  `Funcionario_ID_Funcionario` INT NOT NULL COMMENT '',
  `Veiculo_ID_Veiculo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Viagem`, `Funcionario_ID_Funcionario`, `Veiculo_ID_Veiculo`)  COMMENT '',
  INDEX `fk_Viagem_Funcionario_idx` (`Funcionario_ID_Funcionario` ASC)  COMMENT '',
  INDEX `fk_Viagem_Veiculo1_idx` (`Veiculo_ID_Veiculo` ASC)  COMMENT '',
  CONSTRAINT `fk_Viagem_Funcionario`
    FOREIGN KEY (`Funcionario_ID_Funcionario`)
    REFERENCES `mydb`.`Funcionario` (`ID_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Veiculo1`
    FOREIGN KEY (`Veiculo_ID_Veiculo`)
    REFERENCES `mydb`.`Veiculo` (`ID_Veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gastos` (
  `idGastos` INT NOT NULL COMMENT '',
  `DescricaoGastos` VARCHAR(45) NOT NULL COMMENT '',
  `Imagem` VARCHAR(45) NOT NULL COMMENT '',
  `ValorGasto` VARCHAR(45) NOT NULL COMMENT '',
  `Viagem_ID_Viagem` INT NOT NULL COMMENT '',
  `Viagem_Funcionario_ID_Funcionario` INT NOT NULL COMMENT '',
  `Viagem_Veiculo_ID_Veiculo` INT NOT NULL COMMENT '',
  `TipoGasto` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idGastos`, `Viagem_ID_Viagem`, `Viagem_Funcionario_ID_Funcionario`, `Viagem_Veiculo_ID_Veiculo`)  COMMENT '',
  INDEX `fk_Gastos_Viagem1_idx` (`Viagem_ID_Viagem` ASC, `Viagem_Funcionario_ID_Funcionario` ASC, `Viagem_Veiculo_ID_Veiculo` ASC)  COMMENT '',
  CONSTRAINT `fk_Gastos_Viagem1`
    FOREIGN KEY (`Viagem_ID_Viagem` , `Viagem_Funcionario_ID_Funcionario` , `Viagem_Veiculo_ID_Veiculo`)
    REFERENCES `mydb`.`Viagem` (`ID_Viagem` , `Funcionario_ID_Funcionario` , `Veiculo_ID_Veiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
